// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SigmaTrack.Infrastructure.Data;

#nullable disable

namespace SigmaTrack.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701171653_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_attachments_issue_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.CommentAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<Guid?>("IssueCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_comment_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_comment_attachments");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_comment_attachments_comment_id");

                    b.HasIndex("IssueCommentId")
                        .HasDatabaseName("ix_comment_attachments_issue_comment_id");

                    b.ToTable("comment_attachments", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.GlobalRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_global_roles");

                    b.ToTable("global_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<string>("BlockReason")
                        .HasColumnType("text")
                        .HasColumnName("block_reason");

                    b.Property<Guid?>("BlockedByIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_by_issue_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<string>("Component")
                        .HasColumnType("text")
                        .HasColumnName("component");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomFields")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<double?>("EstimatedHours")
                        .HasColumnType("double precision")
                        .HasColumnName("estimated_hours");

                    b.Property<string>("FixVersion")
                        .HasColumnType("text")
                        .HasColumnName("fix_version");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<bool>("IsReproducible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reproducible");

                    b.Property<double?>("LoggedHours")
                        .HasColumnType("double precision")
                        .HasColumnName("logged_hours");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<double?>("RemainingHours")
                        .HasColumnType("double precision")
                        .HasColumnName("remaining_hours");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StepsToReproduce")
                        .HasColumnType("text")
                        .HasColumnName("steps_to_reproduce");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("integer")
                        .HasColumnName("story_points");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'[]'");

                    b.Property<TimeSpan?>("TimeToFirstResponse")
                        .HasColumnType("interval")
                        .HasColumnName("time_to_first_response");

                    b.Property<TimeSpan?>("TimeToResolution")
                        .HasColumnType("interval")
                        .HasColumnName("time_to_resolution");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_issues_assignee_id");

                    b.HasIndex("BlockedByIssueId")
                        .HasDatabaseName("ix_issues_blocked_by_issue_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_issues_project_id");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_issues_reporter_id");

                    b.HasIndex("SprintId")
                        .HasDatabaseName("ix_issues_sprint_id");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.PrimitiveCollection<List<string>>("Mentions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("mentions");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_comments_author_id");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_comments_issue_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_issue_histories");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_issue_histories_changed_by");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_issue_histories_issue_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_issue_histories_user_id");

                    b.ToTable("issue_histories", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link_type");

                    b.Property<Guid>("SourceIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_issue_id");

                    b.Property<Guid>("TargetIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_issue_id");

                    b.HasKey("Id")
                        .HasName("pk_issue_links");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_issue_links_created_by_user_id");

                    b.HasIndex("SourceIssueId")
                        .HasDatabaseName("ix_issue_links_source_issue_id");

                    b.HasIndex("TargetIssueId")
                        .HasDatabaseName("ix_issue_links_target_issue_id");

                    b.ToTable("issue_links", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Component")
                        .HasColumnType("text")
                        .HasColumnName("component");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_issue_templates");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_issue_templates_project_id");

                    b.ToTable("issue_templates", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueWatcher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WatchedSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watched_since");

                    b.HasKey("Id")
                        .HasName("pk_issue_watchers");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_issue_watchers_issue_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_issue_watchers_user_id");

                    b.ToTable("issue_watchers", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("LinkUrl")
                        .HasColumnType("text")
                        .HasColumnName("link_url");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_projects_creator_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.ProjectCustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Options")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("options")
                        .HasDefaultValueSql("'[]'");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_project_custom_fields");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_custom_fields_project_id");

                    b.ToTable("project_custom_fields", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.ProjectInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invited_at");

                    b.Property<Guid>("InviteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitee_id");

                    b.Property<Guid>("InviterId")
                        .HasColumnType("uuid")
                        .HasColumnName("inviter_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("ProjectRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("project_role_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_project_invitations");

                    b.HasIndex("InviteeId")
                        .HasDatabaseName("ix_project_invitations_invitee_id");

                    b.HasIndex("InviterId")
                        .HasDatabaseName("ix_project_invitations_inviter_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_invitations_project_id");

                    b.HasIndex("ProjectRoleId")
                        .HasDatabaseName("ix_project_invitations_project_role_id");

                    b.ToTable("project_invitations", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("ProjectRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("project_role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_members");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_members_project_id");

                    b.HasIndex("ProjectRoleId")
                        .HasDatabaseName("ix_project_members_project_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_members_user_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.ProjectRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_project_roles");

                    b.ToTable("project_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Полный доступ к настройкам проекта, управлению участниками и всеми задачами.",
                            Name = "Project Manager"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Просмотр проекта, создание, редактирование и закрытие багов/задач.",
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Тестирование функционала, создание баг-репортов, проверка и верификация исправлений.",
                            Name = "QA Engineer"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Доступ только для чтения. Может просматривать задачи и оставлять комментарии без права редактирования.",
                            Name = "Observer"
                        });
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("CommittedPoints")
                        .HasColumnType("integer")
                        .HasColumnName("committed_points");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedPoints")
                        .HasColumnType("integer")
                        .HasColumnName("completed_points");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sprint");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_sprint_project_id");

                    b.ToTable("sprint", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarColor")
                        .HasColumnType("text")
                        .HasColumnName("avatar_color");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("GitHub")
                        .HasColumnType("text")
                        .HasColumnName("git_hub");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_password");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<int>("OnlineStatus")
                        .HasColumnType("integer")
                        .HasColumnName("online_status");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.PrimitiveCollection<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("text")
                        .HasColumnName("status_message");

                    b.Property<string>("Telegram")
                        .HasColumnType("text")
                        .HasColumnName("telegram");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.Issue", "Issue")
                        .WithMany("Attachments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_issues_issue_id");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.CommentAttachment", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.IssueComment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_attachments_comments_comment_id");

                    b.HasOne("SigmaTrack.Domain.Entities.IssueComment", null)
                        .WithMany("Attachments")
                        .HasForeignKey("IssueCommentId")
                        .HasConstraintName("fk_comment_attachments_comments_issue_comment_id");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Issue", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_issues_users_assignee_id");

                    b.HasOne("SigmaTrack.Domain.Entities.Issue", "BlockedByIssue")
                        .WithMany()
                        .HasForeignKey("BlockedByIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_issues_issues_blocked_by_issue_id");

                    b.HasOne("SigmaTrack.Domain.Entities.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_projects_project_id");

                    b.HasOne("SigmaTrack.Domain.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issues_users_reporter_id");

                    b.HasOne("SigmaTrack.Domain.Entities.Sprint", "Sprint")
                        .WithMany("Issues")
                        .HasForeignKey("SprintId")
                        .HasConstraintName("fk_issues_sprint_sprint_id");

                    b.Navigation("Assignee");

                    b.Navigation("BlockedByIssue");

                    b.Navigation("Project");

                    b.Navigation("Reporter");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueComment", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_author_id");

                    b.HasOne("SigmaTrack.Domain.Entities.Issue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_issues_issue_id");

                    b.Navigation("Author");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueHistory", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issue_histories_users_changed_by");

                    b.HasOne("SigmaTrack.Domain.Entities.Issue", "Issue")
                        .WithMany("Histories")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_histories_issues_issue_id");

                    b.HasOne("SigmaTrack.Domain.Entities.User", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_issue_histories_users_user_id");

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueLink", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_links_users_created_by_user_id");

                    b.HasOne("SigmaTrack.Domain.Entities.Issue", "SourceIssue")
                        .WithMany("SourceRelations")
                        .HasForeignKey("SourceIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_links_issues_source_issue_id");

                    b.HasOne("SigmaTrack.Domain.Entities.Issue", "TargetIssue")
                        .WithMany("TargetRelations")
                        .HasForeignKey("TargetIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_links_issues_target_issue_id");

                    b.Navigation("CreatedByUser");

                    b.Navigation("SourceIssue");

                    b.Navigation("TargetIssue");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueTemplate", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_templates_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueWatcher", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.Issue", "Issue")
                        .WithMany("Watchers")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_watchers_issues_issue_id");

                    b.HasOne("SigmaTrack.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_watchers_users_user_id");

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Project", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_creator_id");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.ProjectCustomField", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_custom_fields_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.ProjectInvitation", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.User", "Invitee")
                        .WithMany("IncomingInvitations")
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_invitations_users_invitee_id");

                    b.HasOne("SigmaTrack.Domain.Entities.User", "Inviter")
                        .WithMany("OutgoingInvitations")
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_invitations_users_inviter_id");

                    b.HasOne("SigmaTrack.Domain.Entities.Project", "Project")
                        .WithMany("Invitations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_invitations_projects_project_id");

                    b.HasOne("SigmaTrack.Domain.Entities.ProjectRole", "ProjectRole")
                        .WithMany()
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_invitations_project_roles_project_role_id");

                    b.Navigation("Invitee");

                    b.Navigation("Inviter");

                    b.Navigation("Project");

                    b.Navigation("ProjectRole");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_projects_project_id");

                    b.HasOne("SigmaTrack.Domain.Entities.ProjectRole", "ProjectRole")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_project_roles_project_role_id");

                    b.HasOne("SigmaTrack.Domain.Entities.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_users_user_id");

                    b.Navigation("Project");

                    b.Navigation("ProjectRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Sprint", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.User", b =>
                {
                    b.HasOne("SigmaTrack.Domain.Entities.GlobalRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_global_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.GlobalRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("Histories");

                    b.Navigation("SourceRelations");

                    b.Navigation("TargetRelations");

                    b.Navigation("Watchers");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.IssueComment", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Project", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("Issues");

                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.ProjectRole", b =>
                {
                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("SigmaTrack.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Comments");

                    b.Navigation("IncomingInvitations");

                    b.Navigation("Notifications");

                    b.Navigation("OutgoingInvitations");

                    b.Navigation("ProjectMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
